openapi: 3.0.1
info:
  title: Mock Server
  description: Mock Server
  termsOfService: http://example.com/terms/
  contact:
    email: apiteam@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://example.com
servers:
- url: https://example.com/api/v1
- url: http://example.com/api/v1
tags:
- name: example
  description: Example data
  externalDocs:
    description: Find out more
    url: http://example.com
paths:
  /user:
    $ref: ./paths/user.yml
  /user/{userId}:
    $ref: ./paths/user-by-id.yml
components:
  schemas:
    user:
      $ref: './components/schemas/User.yml'
