/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/user": {
    get: operations["getUser"];
    post: operations["addUser"];
  };
  "/user/{userId}": {
    get: operations["getUserById"];
    patch: operations["updateUser"];
    delete: operations["deleteUser"];
  };
}

export interface operations {
  /** Returns a single user */
  getUser: {
    responses: {
      /** successful operation */
      200: {
        "application/json": components["schemas"]["user"][];
      };
      /** Invalid request */
      400: unknown;
    };
  };
  addUser: {
    requestBody: {
      "application/json": components["schemas"]["user"];
    };
    responses: {
      /** successful operation */
      201: {
        "application/json": components["schemas"]["user"];
      };
      /** Invalid request */
      400: unknown;
      /** Invalid input */
      405: unknown;
    };
  };
  /** Returns a single user */
  getUserById: {
    parameters: {
      path: {
        /** ID of user to return */
        userId: number;
      };
    };
    responses: {
      /** successful operation */
      200: {
        "application/json": components["schemas"]["user"];
      };
      /** Invalid ID supplied */
      400: unknown;
      /** User not found */
      404: unknown;
    };
  };
  updateUser: {
    parameters: {
      path: {
        /** User id to update */
        userId: number;
      };
    };
    requestBody: {
      "application/json": components["schemas"]["user"];
    };
    responses: {
      /** successful operation */
      200: {
        "application/json": components["schemas"]["user"];
      };
      /** Invalid ID supplied */
      400: unknown;
      /** User not found */
      404: unknown;
      /** Validation exception */
      405: unknown;
    };
  };
  deleteUser: {
    parameters: {
      path: {
        /** User id to delete */
        userId: number;
      };
    };
    responses: {
      /** successful operation */
      204: never;
      /** Invalid ID supplied */
      400: unknown;
      /** User not found */
      404: unknown;
    };
  };
}

export interface components {
  schemas: {
    user: {
      id?: number;
      name: string;
      age?: number;
    };
  };
}
